'use strict';

exports.__esModule = true;
var ADD_ARRAY_VALUE = exports.ADD_ARRAY_VALUE = 'redux-form-v5/ADD_ARRAY_VALUE';
var AUTOFILL = exports.AUTOFILL = 'redux-form-v5/AUTOFILL';
var BLUR = exports.BLUR = 'redux-form-v5/BLUR';
var CHANGE = exports.CHANGE = 'redux-form-v5/CHANGE';
var DESTROY = exports.DESTROY = 'redux-form-v5/DESTROY';
var FOCUS = exports.FOCUS = 'redux-form-v5/FOCUS';
var INITIALIZE = exports.INITIALIZE = 'redux-form-v5/INITIALIZE';
var REMOVE_ARRAY_VALUE = exports.REMOVE_ARRAY_VALUE = 'redux-form-v5/REMOVE_ARRAY_VALUE';
var RESET = exports.RESET = 'redux-form-v5/RESET';
var START_ASYNC_VALIDATION = exports.START_ASYNC_VALIDATION = 'redux-form-v5/START_ASYNC_VALIDATION';
var START_SUBMIT = exports.START_SUBMIT = 'redux-form-v5/START_SUBMIT';
var STOP_ASYNC_VALIDATION = exports.STOP_ASYNC_VALIDATION = 'redux-form-v5/STOP_ASYNC_VALIDATION';
var STOP_SUBMIT = exports.STOP_SUBMIT = 'redux-form-v5/STOP_SUBMIT';
var SUBMIT_FAILED = exports.SUBMIT_FAILED = 'redux-form-v5/SUBMIT_FAILED';
var SWAP_ARRAY_VALUES = exports.SWAP_ARRAY_VALUES = 'redux-form-v5/SWAP_ARRAY_VALUES';
var TOUCH = exports.TOUCH = 'redux-form-v5/TOUCH';
var UNTOUCH = exports.UNTOUCH = 'redux-form-v5/UNTOUCH';